#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("be.trojkasoftware.droidCPVanity.Resource", IsApplication=true)]

namespace be.trojkasoftware.droidCPVanity
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int articles24 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_new = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_refresh = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_search = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int member_div2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int member_null = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int member_unknown = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ReputationGraph = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int GridLayout1 = 2131230729;
			
			// aapt resource value: 0x7f08001c
			public const int action_member_add = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int action_member_articles = 2131230749;
			
			// aapt resource value: 0x7f08001b
			public const int action_member_reputation = 2131230747;
			
			// aapt resource value: 0x7f08001f
			public const int action_refresh = 2131230751;
			
			// aapt resource value: 0x7f08001e
			public const int action_search = 2131230750;
			
			// aapt resource value: 0x7f08001a
			public const int frameLayoutFragmentContainer = 2131230746;
			
			// aapt resource value: 0x7f08000a
			public const int imageViewMemberImage = 2131230730;
			
			// aapt resource value: 0x7f080015
			public const int imageViewReputationGraph = 2131230741;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout1 = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int listViewArticles = 2131230727;
			
			// aapt resource value: 0x7f080019
			public const int listViewFeed = 2131230745;
			
			// aapt resource value: 0x7f08000e
			public const int memberListView = 2131230734;
			
			// aapt resource value: 0x7f080008
			public const int memberPager = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int relativeLayout1 = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int textView1 = 2131230726;
			
			// aapt resource value: 0x7f08000f
			public const int textView2 = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int textViewArticleCnt = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int textViewArticleRating = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int textViewBlogCnt = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int textViewBlogRating = 2131230740;
			
			// aapt resource value: 0x7f080002
			public const int textViewDate = 2131230722;
			
			// aapt resource value: 0x7f080018
			public const int textViewFeedName = 2131230744;
			
			// aapt resource value: 0x7f08000b
			public const int textViewMemberName = 2131230731;
			
			// aapt resource value: 0x7f080010
			public const int textViewMemberReputation = 2131230736;
			
			// aapt resource value: 0x7f08000d
			public const int textViewPostCnt = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int textViewReputation = 2131230732;
			
			// aapt resource value: 0x7f080017
			public const int textViewRssItemDescription = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int textViewRssItemTitle = 2131230742;
			
			// aapt resource value: 0x7f080003
			public const int textViewScore = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int textViewTitle = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int textViewVotes = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CodeProjectLoungeFeedLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CodeProjectMemberArticlesItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CodeProjectMemberArticlesLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CodeProjectMemberLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CodeProjectMemberListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CodeProjectMemberListLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int CodeProjectMemberProfileLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int CodeProjectMemberReputationLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int CodeProjectRssFeedItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int CodeProjectRssFeedLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int MainLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SettingsLayout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int codeproject_member_articles_actions = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int codeproject_member_profile_actions = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int main_actions = 2131165186;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int search_hint = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int searchable = 2130968577;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
