// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using be.trojkasoftware.portableCPVanity;
using be.trojkasoftware.portableCPVanity.RssFeeds;

namespace touchCPVanity
{
	public partial class ArticleCategoryViewController : UITableViewController
	{
		public ArticleCategoryViewController (IntPtr handle) : base (handle)
		{
		}

		public IFeedReceiver FeedReceiver {
			get;
			set;
		}

		public override void DidReceiveMemoryWarning ()
		{
			base.DidReceiveMemoryWarning ();
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
		}

		public override int NumberOfSections (UITableView tableView)
		{
			return 1;
		}

		public override int RowsInSection (UITableView tableview, int section)
		{
			return CodeProjectArticleFeed.Categories.Count;
		}

		public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			var cell = tableView.DequeueReusableCell ("RSSArticleCategoryCell");

			(cell.ViewWithTag (nameTag) as UILabel).Text = CodeProjectArticleFeed.Categories[indexPath.Row].Name;

			return cell;
		}

		public override void RowSelected (UITableView tableView, NSIndexPath indexPath)
		{
			TableView.DeselectRow (indexPath, false);
			this.FeedReceiver.ItemFeed = CodeProjectArticleFeed.GetFeed(CodeProjectArticleFeed.Categories[indexPath.Row].Id);

			this.NavigationController.PopViewControllerAnimated (true);
		}

		private static int nameTag = 100;
	}
}
