// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace touchCPVanity
{
	public partial class CodeProjectMember : UIView
	{
		public CodeProjectMember (IntPtr handle) : base (handle)
		{
		}
	}
}
